// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKoelnQ1WVsp1ffsTrnWh78quTqKtjGmc',
    appId: '1:552894342862:web:4b644a52cb4f601ae5d29f',
    messagingSenderId: '552894342862',
    projectId: 'flutter-authen-87ad8',
    authDomain: 'flutter-authen-87ad8.firebaseapp.com',
    storageBucket: 'flutter-authen-87ad8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKh-0qA4GRGX_8BiQu2K5HUPpDY-bdKAY',
    appId: '1:552894342862:android:33a78fa3563939e5e5d29f',
    messagingSenderId: '552894342862',
    projectId: 'flutter-authen-87ad8',
    storageBucket: 'flutter-authen-87ad8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYhuJYQ9UgaYttJUPyXvslsxdEog-R4Lw',
    appId: '1:552894342862:ios:384d8eb2e08ac136e5d29f',
    messagingSenderId: '552894342862',
    projectId: 'flutter-authen-87ad8',
    storageBucket: 'flutter-authen-87ad8.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYhuJYQ9UgaYttJUPyXvslsxdEog-R4Lw',
    appId: '1:552894342862:ios:384d8eb2e08ac136e5d29f',
    messagingSenderId: '552894342862',
    projectId: 'flutter-authen-87ad8',
    storageBucket: 'flutter-authen-87ad8.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKoelnQ1WVsp1ffsTrnWh78quTqKtjGmc',
    appId: '1:552894342862:web:9dda7541a208a67ae5d29f',
    messagingSenderId: '552894342862',
    projectId: 'flutter-authen-87ad8',
    authDomain: 'flutter-authen-87ad8.firebaseapp.com',
    storageBucket: 'flutter-authen-87ad8.firebasestorage.app',
  );
}
